### ISSUE TITLE
the data of item ranking

### ISSUE THREAD

**Issue by ConanCui** [cheungdaven/DeepRec#1]
I find the data in "test_item_ranking.py"  is still in the range of 1-5, should it be 0/1 in the ranking problem? For example in mlp and GMF model

**Comment by cheungdaven** [comment]
@ConanCui Yeah, it should be 0/1, I have updated it. You can actually provide a file with 0/1 labels instead of rating scores.

**Comment by ConanCui** [comment]
Thanks for your kindly response
