### ISSUE TITLE
about AUTO-REC MOEDEL

### ISSUE THREAD

**Issue by liheyong** [cheungdaven/DeepRec#22]
作者您好，
因为自动编码机那地方，是评分矩阵输入到隐藏层编码完成，隐藏层到输出层就得到预测评分矩阵。
请问作者，这个代码的意思是对评分矩阵进行编码，然后解码，从而重构并补全评分矩阵吗？

作者您好，
我想问下您的基于项目的编码协同过滤中训练之后，在哪里保存的训练参数呢？还是说系统自动保存？

**Comment by liheyong** [comment]
作者您给出的损失函数好像没有按照论文里的公式给出。所有导致看不懂这个损失函数是什么构造。

**Comment by cheungdaven** [comment]
对autorec的理解没问题。
参数保存，暂时没有写这个，你可以调用tf的save保存。

**Comment by liheyong** [comment]
好的，谢谢您的解答！
