### ISSUE TITLE
关于AutoSVD++的content information处理

### ISSUE THREAD

**Issue by liheyong** [cheungdaven/DeepRec#23]
您好！最近细读了您的论文：AutoSVD++: An Efficient Hybrid Collaborative Filtering Model
via Contractive Auto-encoders。

想对其中的自编码机处理content information的过程深入了解。在您的github没有找到处理item_feature的相关程序。本人水平有限，对content information的处理没能力复现。
请问您方便指点下content information的处理细节吗
（from    'item side information'     to     'latent  vector'    of item）

**Comment by cheungdaven** [comment]
我用的CAE的开源代码学的feature.

**Comment by jiangjjjj** [comment]
请问，AutoSVD++这篇将项目的特征矩阵提取出来的操作，输入数据是什么？

**Comment by jiangjjjj** [comment]
> 我用的CAE的开源代码学的feature.

请问可以放一下CAE部分的相关代码吗
