### ISSUE TITLE
Why HR and MRR are getting smaller and smaller when training with AttRec

### ISSUE THREAD

**Issue by linh47** [cheungdaven/DeepRec#26]
The first output is

> Epoch: 0005; 
> HR@50:0.5005302226935313
> MRR:0.08745163611856224
> AUC:0.9075360408864436
> 2020-02-07 09:50:03

then

> 
> Epoch: 0123; 
> HR@50:0.46977730646871685
> MRR:0.08698753010475276
> AUC:0.8941231973552161
> 2020-02-07 10:00:21

Aren't these two bigger the better????

**Comment by linh47** [comment]
您好，我跑完了5000个epoch，我发现越训练这两个值越小，是不是损失函数或者训练过程有问题呢？
希望能得到您的回复…

**Comment by cheungdaven** [comment]
@linh47 到了一定步骤会过拟合，一般不需要那么长时间的训练。
