### ISSUE TITLE
code with regard to "Next Item Recommendation with Self-Atention"

### ISSUE THREAD

**Issue by DebonairLi** [cheungdaven/DeepRec#3]
您好，有幸拜读您的这篇文章”Next Item Recommendation with Self-Atention”。所以想问一下您有没有这篇论文的代码，作为刚入学推荐系统的小白，还是希望再拜读一下您的代码，非常感谢！（知道您是中国人，就不写英语了哈哈）

**Comment by cheungdaven** [comment]
> 您好，有幸拜读您的这篇文章”Next Item Recommendation with Self-Atention”。所以想问一下您有没有这篇论文的代码，作为刚入学推荐系统的小白，还是希望再拜读一下您的代码，非常感谢！（知道您是中国人，就不写英语了哈哈）

我会尽快开放代码。

**Comment by zippeurfou** [comment]
@cheungdaven Any update on this?

**Comment by CherryFeng** [comment]
请问能开放“Next Item Recommendation with Self-Atention”论文的代码吗？

**Comment by cheungdaven** [comment]
@DebonairLi @zippeurfou @CherryFeng I have added the code of AttRec, Caser and PRME. The code is messy, I will clean them soon. Sorry for the delay.
