### ISSUE TITLE
About hit radio@50 in the evaluation of AttRec 

### ISSUE THREAD

**Issue by blcunlp** [cheungdaven/DeepRec#31]
hi,
In the evaluation process of AttRec, when calculating the recommendation item rank of each user, why use the negative items instead of all items?
this code in: DeepRec/utils/evaluation/SeqRecMetrics.py--->def evaluate1(self)
![image](https://user-images.githubusercontent.com/31537780/82977711-3f997380-a015-11ea-961d-536ece110d2f.png)

In my understanding, It should be to calculate the score of each user and all items,  then rank them,  and finally take the top 50 to calculate HT@50.

Calculate it the way the code says,  it does not have any positive items in the prediction process.

**Comment by cheungdaven** [comment]
Usually, we only consider recommending those items that the user has never seen.  If an item is liked by the user, we don't want to repeatedly recommend it to him.
