### ISSUE TITLE
missing dataset processing procedure for testSeqRec.py

### ISSUE THREAD

**Issue by ibunny01** [cheungdaven/DeepRec#7]
In file `testSeqRec.py` I find this piece of code:
```python
        if args.model == "AttRec":
            train_data = DataSet(path="../Data/ml100k/temp/train.dat", sep="\t",header=['user', 'item', 'rating', 'time'],isTrain=True, seq_len=5, target_len=3, num_users=943, num_items=1682)
            test_data = DataSet(path="../Data/ml100k/temp/test.dat", sep="\t", header=['user', 'item', 'rating', 'time'], user_map=train_data.user_map, item_map=train_data.item_map)
```
but I can't find `ml100k/temp/train.dat` and `ml100k/temp/test.dat`, there is only `movielens_100k.dat` file in the `ml100k/` folder, could you please provide the data processing procedure?

**Comment by ibunny01** [comment]
Is it the same as `load_data_neg` function in `load_data_ranking.py` file?

**Comment by cheungdaven** [comment]
@ibunny01 sorry, I forgot to upload the file.  I will do it soon. Thanks

**Comment by cheungdaven** [comment]
https://github.com/cheungdaven/DeepRec/commit/072bc1b300280795439e7988e9e96e882745ed67
