### ISSUE TITLE
Try run AttRec but the HR sorce is too low

### ISSUE THREAD

**Issue by molybdenumyz** [cheungdaven/DeepRec#8]
HR@50:0.3753976670201485
MRR:0.053446402676701824
AUC:0.8771433443062608
92456
Epoch: 0543; (943, 100)
how can I reproduce effect

**Comment by cheungdaven** [comment]
It seems that I put a wrong loss there,  I will revise it, thank you for pointing out.

**Comment by cheungdaven** [comment]
https://github.com/cheungdaven/DeepRec/commit/a6c93234c876777d9fe45ee719eff72c41ae1c49 I have updated the loss function,  It should reproduce the reported results now. If you have any other questions, just leave me a message here.

**Comment by cheungdaven** [comment]
The best results I can get now:
HR@50:0.5312831389183457
MRR:0.0911185864781581
AUC:0.909033997832354

**Comment by DebonairLi** [comment]
> The best results I can get now:
> HR@50:0.5312831389183457
> MRR:0.0911185864781581
> AUC:0.909033997832354

In your code, maybe there aren't any parts to calculate the best HR, MRR，we need to revise it,right?

**Comment by cheungdaven** [comment]
yeah, there are not. I will keep improving the repo. Thanks.
